# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages_robocup_ssl_detection_tracked.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages_robocup_ssl_detection_tracked.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n,messages_robocup_ssl_detection_tracked.proto\"\x1f\n\x07Vector2\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\t\n\x01z\x18\x03 \x02(\x02\"5\n\x07RobotId\x12\n\n\x02id\x18\x01 \x02(\r\x12\x1e\n\nteam_color\x18\x02 \x02(\x0e\x32\n.TeamColor\"O\n\x0bTrackedBall\x12\x15\n\x03pos\x18\x01 \x02(\x0b\x32\x08.Vector3\x12\x15\n\x03vel\x18\x02 \x01(\x0b\x32\x08.Vector3\x12\x12\n\nvisibility\x18\x03 \x01(\x02\"\xa3\x01\n\nKickedBall\x12\x15\n\x03pos\x18\x01 \x02(\x0b\x32\x08.Vector2\x12\x15\n\x03vel\x18\x02 \x02(\x0b\x32\x08.Vector3\x12\x17\n\x0fstart_timestamp\x18\x03 \x02(\x01\x12\x16\n\x0estop_timestamp\x18\x04 \x01(\x01\x12\x1a\n\x08stop_pos\x18\x05 \x01(\x0b\x32\x08.Vector2\x12\x1a\n\x08robot_id\x18\x06 \x01(\x0b\x32\x08.RobotId\"\x96\x01\n\x0cTrackedRobot\x12\x1a\n\x08robot_id\x18\x01 \x02(\x0b\x32\x08.RobotId\x12\x15\n\x03pos\x18\x02 \x02(\x0b\x32\x08.Vector2\x12\x13\n\x0borientation\x18\x03 \x02(\x02\x12\x15\n\x03vel\x18\x04 \x01(\x0b\x32\x08.Vector2\x12\x13\n\x0bvel_angular\x18\x05 \x01(\x02\x12\x12\n\nvisibility\x18\x06 \x01(\x02\"\xb8\x01\n\x0cTrackedFrame\x12\x14\n\x0c\x66rame_number\x18\x01 \x02(\r\x12\x11\n\ttimestamp\x18\x02 \x02(\x01\x12\x1b\n\x05\x62\x61lls\x18\x03 \x03(\x0b\x32\x0c.TrackedBall\x12\x1d\n\x06robots\x18\x04 \x03(\x0b\x32\r.TrackedRobot\x12 \n\x0bkicked_ball\x18\x05 \x01(\x0b\x32\x0b.KickedBall\x12!\n\x0c\x63\x61pabilities\x18\x06 \x03(\x0e\x32\x0b.Capability*O\n\tTeamColor\x12\x16\n\x12TEAM_COLOR_UNKNOWN\x10\x00\x12\x15\n\x11TEAM_COLOR_YELLOW\x10\x01\x12\x13\n\x0fTEAM_COLOR_BLUE\x10\x02*\x92\x01\n\nCapability\x12\x16\n\x12\x43\x41PABILITY_UNKNOWN\x10\x00\x12\"\n\x1e\x43\x41PABILITY_DETECT_FLYING_BALLS\x10\x01\x12$\n CAPABILITY_DETECT_MULTIPLE_BALLS\x10\x02\x12\"\n\x1e\x43\x41PABILITY_DETECT_KICKED_BALLS\x10\x03')
)

_TEAMCOLOR = _descriptor.EnumDescriptor(
  name='TeamColor',
  full_name='TeamColor',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TEAM_COLOR_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEAM_COLOR_YELLOW', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEAM_COLOR_BLUE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=767,
  serialized_end=846,
)
_sym_db.RegisterEnumDescriptor(_TEAMCOLOR)

TeamColor = enum_type_wrapper.EnumTypeWrapper(_TEAMCOLOR)
_CAPABILITY = _descriptor.EnumDescriptor(
  name='Capability',
  full_name='Capability',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CAPABILITY_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAPABILITY_DETECT_FLYING_BALLS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAPABILITY_DETECT_MULTIPLE_BALLS', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAPABILITY_DETECT_KICKED_BALLS', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=849,
  serialized_end=995,
)
_sym_db.RegisterEnumDescriptor(_CAPABILITY)

Capability = enum_type_wrapper.EnumTypeWrapper(_CAPABILITY)
TEAM_COLOR_UNKNOWN = 0
TEAM_COLOR_YELLOW = 1
TEAM_COLOR_BLUE = 2
CAPABILITY_UNKNOWN = 0
CAPABILITY_DETECT_FLYING_BALLS = 1
CAPABILITY_DETECT_MULTIPLE_BALLS = 2
CAPABILITY_DETECT_KICKED_BALLS = 3



_VECTOR2 = _descriptor.Descriptor(
  name='Vector2',
  full_name='Vector2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vector2.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vector2.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=79,
)


_VECTOR3 = _descriptor.Descriptor(
  name='Vector3',
  full_name='Vector3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vector3.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vector3.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='Vector3.z', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=123,
)


_ROBOTID = _descriptor.Descriptor(
  name='RobotId',
  full_name='RobotId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RobotId.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='team_color', full_name='RobotId.team_color', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=178,
)


_TRACKEDBALL = _descriptor.Descriptor(
  name='TrackedBall',
  full_name='TrackedBall',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='TrackedBall.pos', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vel', full_name='TrackedBall.vel', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visibility', full_name='TrackedBall.visibility', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=259,
)


_KICKEDBALL = _descriptor.Descriptor(
  name='KickedBall',
  full_name='KickedBall',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='KickedBall.pos', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vel', full_name='KickedBall.vel', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_timestamp', full_name='KickedBall.start_timestamp', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stop_timestamp', full_name='KickedBall.stop_timestamp', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stop_pos', full_name='KickedBall.stop_pos', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='KickedBall.robot_id', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=425,
)


_TRACKEDROBOT = _descriptor.Descriptor(
  name='TrackedRobot',
  full_name='TrackedRobot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='TrackedRobot.robot_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='TrackedRobot.pos', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='TrackedRobot.orientation', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vel', full_name='TrackedRobot.vel', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vel_angular', full_name='TrackedRobot.vel_angular', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visibility', full_name='TrackedRobot.visibility', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=578,
)


_TRACKEDFRAME = _descriptor.Descriptor(
  name='TrackedFrame',
  full_name='TrackedFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_number', full_name='TrackedFrame.frame_number', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='TrackedFrame.timestamp', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balls', full_name='TrackedFrame.balls', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='robots', full_name='TrackedFrame.robots', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kicked_ball', full_name='TrackedFrame.kicked_ball', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='capabilities', full_name='TrackedFrame.capabilities', index=5,
      number=6, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=581,
  serialized_end=765,
)

_ROBOTID.fields_by_name['team_color'].enum_type = _TEAMCOLOR
_TRACKEDBALL.fields_by_name['pos'].message_type = _VECTOR3
_TRACKEDBALL.fields_by_name['vel'].message_type = _VECTOR3
_KICKEDBALL.fields_by_name['pos'].message_type = _VECTOR2
_KICKEDBALL.fields_by_name['vel'].message_type = _VECTOR3
_KICKEDBALL.fields_by_name['stop_pos'].message_type = _VECTOR2
_KICKEDBALL.fields_by_name['robot_id'].message_type = _ROBOTID
_TRACKEDROBOT.fields_by_name['robot_id'].message_type = _ROBOTID
_TRACKEDROBOT.fields_by_name['pos'].message_type = _VECTOR2
_TRACKEDROBOT.fields_by_name['vel'].message_type = _VECTOR2
_TRACKEDFRAME.fields_by_name['balls'].message_type = _TRACKEDBALL
_TRACKEDFRAME.fields_by_name['robots'].message_type = _TRACKEDROBOT
_TRACKEDFRAME.fields_by_name['kicked_ball'].message_type = _KICKEDBALL
_TRACKEDFRAME.fields_by_name['capabilities'].enum_type = _CAPABILITY
DESCRIPTOR.message_types_by_name['Vector2'] = _VECTOR2
DESCRIPTOR.message_types_by_name['Vector3'] = _VECTOR3
DESCRIPTOR.message_types_by_name['RobotId'] = _ROBOTID
DESCRIPTOR.message_types_by_name['TrackedBall'] = _TRACKEDBALL
DESCRIPTOR.message_types_by_name['KickedBall'] = _KICKEDBALL
DESCRIPTOR.message_types_by_name['TrackedRobot'] = _TRACKEDROBOT
DESCRIPTOR.message_types_by_name['TrackedFrame'] = _TRACKEDFRAME
DESCRIPTOR.enum_types_by_name['TeamColor'] = _TEAMCOLOR
DESCRIPTOR.enum_types_by_name['Capability'] = _CAPABILITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector2 = _reflection.GeneratedProtocolMessageType('Vector2', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR2,
  __module__ = 'messages_robocup_ssl_detection_tracked_pb2'
  # @@protoc_insertion_point(class_scope:Vector2)
  ))
_sym_db.RegisterMessage(Vector2)

Vector3 = _reflection.GeneratedProtocolMessageType('Vector3', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR3,
  __module__ = 'messages_robocup_ssl_detection_tracked_pb2'
  # @@protoc_insertion_point(class_scope:Vector3)
  ))
_sym_db.RegisterMessage(Vector3)

RobotId = _reflection.GeneratedProtocolMessageType('RobotId', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTID,
  __module__ = 'messages_robocup_ssl_detection_tracked_pb2'
  # @@protoc_insertion_point(class_scope:RobotId)
  ))
_sym_db.RegisterMessage(RobotId)

TrackedBall = _reflection.GeneratedProtocolMessageType('TrackedBall', (_message.Message,), dict(
  DESCRIPTOR = _TRACKEDBALL,
  __module__ = 'messages_robocup_ssl_detection_tracked_pb2'
  # @@protoc_insertion_point(class_scope:TrackedBall)
  ))
_sym_db.RegisterMessage(TrackedBall)

KickedBall = _reflection.GeneratedProtocolMessageType('KickedBall', (_message.Message,), dict(
  DESCRIPTOR = _KICKEDBALL,
  __module__ = 'messages_robocup_ssl_detection_tracked_pb2'
  # @@protoc_insertion_point(class_scope:KickedBall)
  ))
_sym_db.RegisterMessage(KickedBall)

TrackedRobot = _reflection.GeneratedProtocolMessageType('TrackedRobot', (_message.Message,), dict(
  DESCRIPTOR = _TRACKEDROBOT,
  __module__ = 'messages_robocup_ssl_detection_tracked_pb2'
  # @@protoc_insertion_point(class_scope:TrackedRobot)
  ))
_sym_db.RegisterMessage(TrackedRobot)

TrackedFrame = _reflection.GeneratedProtocolMessageType('TrackedFrame', (_message.Message,), dict(
  DESCRIPTOR = _TRACKEDFRAME,
  __module__ = 'messages_robocup_ssl_detection_tracked_pb2'
  # @@protoc_insertion_point(class_scope:TrackedFrame)
  ))
_sym_db.RegisterMessage(TrackedFrame)


# @@protoc_insertion_point(module_scope)
